<?php use App\Helpers\Csrf; $editing = !empty($user['IdUsuario']); ?>
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1"><?= $editing ? 'Editar usuario' : 'Nuevo usuario' ?></h1><p class="text-secondary mb-0">Complete los datos y asigne el nivel de acceso.</p></div><a class="btn btn-outline-secondary" href="index.php?route=usuarios">Volver</a></div>
<?php if ($errors): ?><div class="alert alert-danger"><strong>Revise la información:</strong><ul class="mb-0"><?php foreach ($errors as $error): ?><li><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<div class="card shadow-sm"><div class="card-body p-4"><form method="post" action="index.php?route=<?= $editing ? 'usuarios/actualizar' : 'usuarios/guardar' ?>" autocomplete="off">
<input type="hidden" name="csrf_token" value="<?= Csrf::token() ?>"><?php if ($editing): ?><input type="hidden" name="id" value="<?= (int)$user['IdUsuario'] ?>"><?php endif; ?>
<div class="row g-3">
<div class="col-md-6"><label class="form-label">Nombres</label><input class="form-control" name="names" maxlength="100" required value="<?= htmlspecialchars($user['Nombres'] ?? $user['names'] ?? '', ENT_QUOTES, 'UTF-8') ?>"></div>
<div class="col-md-6"><label class="form-label">Apellidos</label><input class="form-control" name="surnames" maxlength="100" required value="<?= htmlspecialchars($user['Apellidos'] ?? $user['surnames'] ?? '', ENT_QUOTES, 'UTF-8') ?>"></div>
<div class="col-md-6"><label class="form-label">Usuario</label><input class="form-control" name="username" maxlength="50" required value="<?= htmlspecialchars($user['NombreUsuario'] ?? $user['username'] ?? '', ENT_QUOTES, 'UTF-8') ?>"></div>
<div class="col-md-6"><label class="form-label">Correo</label><input class="form-control" type="email" name="email" maxlength="150" required value="<?= htmlspecialchars($user['Correo'] ?? $user['email'] ?? '', ENT_QUOTES, 'UTF-8') ?>"></div>
<div class="col-md-6"><label class="form-label">Rol</label><select class="form-select" name="role_id" required><option value="">Seleccione...</option><?php $roleValue = (int)($user['IdRol'] ?? $user['role_id'] ?? 0); foreach ($roles as $role): ?><option value="<?= (int)$role['IdRol'] ?>" <?= $roleValue === (int)$role['IdRol'] ? 'selected' : '' ?>><?= htmlspecialchars($role['Nombre'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></div>
<div class="col-md-6"><label class="form-label"><?= $editing ? 'Nueva contraseña (opcional)' : 'Contraseña temporal' ?></label><input class="form-control" type="password" name="password" <?= $editing ? '' : 'required' ?> minlength="8" maxlength="128"><div class="form-text">Mayúscula, minúscula, número y carácter especial.</div></div>
<div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="state" id="state" <?= !$editing || (int)($user['Estado'] ?? $user['state'] ?? 1) === 1 ? 'checked' : '' ?>><label class="form-check-label" for="state">Usuario activo</label></div></div>
<div class="col-12"><button class="btn btn-primary">Guardar usuario</button></div>
</div></form></div></div>
