<?php
namespace App\Controllers;
use App\Helpers\{Authorization,Csrf,Flash,Response,View,Audit};
use App\Middleware\AuthMiddleware;
use App\Models\Product;
final class ProductController
{
 public function index(): void { AuthMiddleware::handle();Authorization::require('productos.ver');$search=trim((string)($_GET['q']??''));$category=(int)($_GET['categoria']??0);$status=(string)($_GET['estado']??'');$catalogs=Product::catalogs();View::render('productos/index',['title'=>'Productos','products'=>Product::all($search,$category,$status),'catalogs'=>$catalogs,'filters'=>compact('search','category','status')]); }
 public function create(): void { AuthMiddleware::handle();Authorization::require('productos.crear');View::render('productos/form',['title'=>'Nuevo producto','product'=>null,'catalogs'=>Product::catalogs()]); }
 public function edit(): void { AuthMiddleware::handle();Authorization::require('productos.editar');$p=Product::find((int)($_GET['id']??0));if(!$p){http_response_code(404);exit('Producto no encontrado.');}View::render('productos/form',['title'=>'Editar producto','product'=>$p,'catalogs'=>Product::catalogs()]); }
 public function save(): void { AuthMiddleware::handle();$id=(int)($_POST['id']??0);Authorization::require($id?'productos.editar':'productos.crear');if(!Csrf::validate($_POST['csrf_token']??null))exit('Solicitud inválida.');$d=$this->data();if($d['codigo']===''||mb_strlen($d['nombre'])<2||$d['maximo']<$d['minimo']){Flash::add('danger','Revise los datos: código, nombre y límites de stock.');Response::redirect('index.php?route='.($id?'productos/editar&id='.$id:'productos/crear'));}try{if($id){$d['id']=$id;unset($d['usuario']);Product::update($d);}else{Product::create($d);}Audit::log($id?'ACTUALIZAR':'CREAR','Productos','EXITOSO','Producto',$d['codigo']);Flash::add('success','Producto guardado correctamente.');}catch(\Throwable $e){Flash::add('danger','No fue posible guardar. Verifique que código y código de barras no estén repetidos.');}Response::redirect('index.php?route=productos'); }
 public function toggle(): void { AuthMiddleware::handle();Authorization::require('productos.estado');if(!Csrf::validate($_POST['csrf_token']??null))exit('Solicitud inválida.');Product::toggle((int)($_POST['id']??0));Flash::add('success','Estado del producto actualizado.');Response::redirect('index.php?route=productos'); }
 private function data(): array { return ['codigo'=>strtoupper(trim((string)($_POST['codigo']??''))),'barras'=>trim((string)($_POST['barras']??''))?:null,'nombre'=>trim((string)($_POST['nombre']??'')),'descripcion'=>trim((string)($_POST['descripcion']??'')),'categoria'=>(int)($_POST['categoria']??0),'unidad'=>(int)($_POST['unidad']??0),'marca'=>(int)($_POST['marca']??0)?:null,'proveedor'=>(int)($_POST['proveedor']??0)?:null,'compra'=>(float)($_POST['compra']??0),'venta'=>(float)($_POST['venta']??0),'minimo'=>(float)($_POST['minimo']??0),'maximo'=>(float)($_POST['maximo']??0),'usuario'=>(int)$_SESSION['user']['id']]; }
}
